# Generated by Django 5.1.2 on 2025-05-14 11:22

import django.core.validators
import django.utils.timezone
import excel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="history",
            name="file",
            field=models.FileField(
                upload_to=excel.models.dir_path_name,
                validators=[
                    django.core.validators.FileExtensionValidator(["xlsx", "xlsm"])
                ],
            ),
        ),
    ]
